/**
 * site.config.js — the single source of truth for everything personal.
 *
 * This is the file to edit. Nothing else in `src/` hardcodes a name, a link,
 * a project or a piece of copy: the 3D rooms, the SEO tags, the hero title and
 * the screen-reader fallback all read from here.
 *
 * It is imported both by the running app (Vite) and by the asset generator
 * (`scripts/art/generate.mjs`), so keep it plain ESM — no JSX, no imports.
 *
 * Content below was generated from the GitHub account @WenOwen.
 */

/* ------------------------------------------------------------------ *
 * Identity
 * ------------------------------------------------------------------ */
export const identity = {
  /** Shown as the giant hand-drawn hero title in the corridor. Keep it to 3–5 chars. */
  handle: 'WU5',
  /** Full display name. */
  name: 'wu5',
  /** GitHub login. */
  login: 'WenOwen',
  /** Shown as the <tagline /> under the hero title. */
  tagline: ['<', 'creative', 'developer', '/>'],
  /** About room headline. */
  aboutTitle: 'WU5',
  aboutSubtitle: 'AI Engineer / Creative Developer',
  /** One-line positioning. Keep it ASCII — the 3D fonts have no CJK coverage. */
  bio: 'AI engineering - agent systems - research tooling',
  location: 'China',
  email: 'wenowen@example.com',
  avatar: 'https://avatars.githubusercontent.com/u/128898998?v=4',
  /** Where the site will live once deployed — used for canonical/OG URLs. */
  siteUrl: 'https://wu5.dev',
};

/* ------------------------------------------------------------------ *
 * Social links (Contact room signposts, nav, SEO)
 * ------------------------------------------------------------------ */
export const socials = [
  { id: 'github', label: 'GITHUB', url: 'https://github.com/WenOwen' },
  { id: 'linkedin', label: 'LINKEDIN', url: 'https://www.linkedin.com/' },
  { id: 'message', label: 'MESSAGE', url: `mailto:${identity.email}` },
  { id: 'x', label: 'X', url: 'https://x.com/' },
  { id: 'rss', label: 'BLOG', url: 'https://github.com/WenOwen?tab=repositories' },
];

/* ------------------------------------------------------------------ *
 * Gallery projects — shown as cards on the clothesline.
 * `art` becomes /textures/gallery/<art>.webp (+ `_painted`).
 * `tech` entries become /textures/gallery/<tech>logo.webp
 * ------------------------------------------------------------------ */
export const projects = [
  {
    id: 'wu5-dev-flow',
    title: 'WU5 DEV FLOW',
    art: 'devflow',
    url: 'https://github.com/WenOwen/wu5-dev-flow',
    description:
      'Auditable SDD, strict TDD and a safe Git workflow, packaged as a reusable skill for Codex and Python projects. Enforces a spec-first loop with reviewable checkpoints.',
    tech: ['python', 'git', 'markdown'],
    stars: 17,
  },
  {
    id: 'yongxu',
    title: 'YONGXU',
    art: 'yongxu',
    url: 'https://github.com/WenOwen/yongxu',
    description:
      'An AI company operating-system skeleton: org structure, agent roles, task routing, governance and evolution loops modelled as first-class primitives.',
    tech: ['python', 'sqlite', 'markdown'],
    stars: 0,
  },
  {
    id: 'deepdelta-aero',
    title: 'DEEPDELTA AERO',
    art: 'aero',
    url: 'https://github.com/WenOwen/DeepDelta-Aero',
    description:
      'Deep delta-learning for aerodynamics — predicting the aerodynamic performance of axial compressor blades with neural surrogates instead of full CFD sweeps.',
    tech: ['python', 'pytorch', 'numpy'],
    stars: 0,
  },
  {
    id: 'entropy-skills',
    title: 'ENTROPY SKILLS',
    art: 'entropy',
    url: 'https://github.com/WenOwen/entropy-skills',
    description:
      'Diagnoses routing conflicts, capability overlap and maintenance entropy across a local Agent Skills collection, then reports what to merge, split or retire.',
    tech: ['python', 'markdown'],
    stars: 0,
  },
  {
    id: 'wu5-dukou',
    title: 'WU5 DUKOU',
    art: 'dukou',
    url: 'https://github.com/WenOwen/wu5-dukou',
    description:
      'A safe Markdown draft-distribution tool and skill that formats and publishes writing to WeChat, Douyin and Bilibili without leaking unpublished drafts.',
    tech: ['javascript', 'node', 'markdown'],
    stars: 0,
  },
  {
    id: 'chrome-translate',
    title: 'TRANSLATE',
    art: 'translate',
    url: 'https://github.com/WenOwen/chrome-translate-extension',
    description:
      'A one-click Chrome extension that translates English text to Chinese in place, built to stay out of the way while reading technical documentation.',
    tech: ['javascript', 'html', 'css'],
    stars: 0,
  },
];

/** Tech badges rendered along the bottom of each gallery card and in the logo row.
 *  Every `file` here gets an art file generated by `npm run art`.
 *  Every stem used in `projects[].tech` must appear here, or the badge is dropped. */
export const techLogos = [
  { file: 'pythonlogo', label: 'PY' },
  { file: 'typescriptlogo', label: 'TS' },
  { file: 'javascriptlogo', label: 'JS' },
  { file: 'reactlogo', label: 'RE' },
  { file: 'nodelogo', label: 'ND' },
  { file: 'gitlogo', label: 'GIT' },
  { file: 'pytorchlogo', label: 'PT' },
  { file: 'numpylogo', label: 'NP' },
  { file: 'sqlitelogo', label: 'SQL' },
  { file: 'dockerlogo', label: 'DK' },
  { file: 'htmllogo', label: 'HTML' },
  { file: 'csslogo', label: 'CSS' },
  { file: 'tailwindlogo', label: 'TW' },
  { file: 'markdownlogo', label: 'MD' },
];

/* ------------------------------------------------------------------ *
 * About room — skill balloons and award plaques
 * ------------------------------------------------------------------ */
export const balloons = [
  { file: 'reactduzybalon', label: 'React', size: 'big' },
  { file: 'threejsduzybalon', label: 'Three.js', size: 'big' },
  { file: 'GSAPduzybalon', label: 'GSAP', size: 'big' },
  { file: 'JSSREDNIBALON', label: 'JS', size: 'mid' },
  { file: 'csssrednibalon', label: 'CSS', size: 'mid' },
  { file: 'nextjssrednibalon', label: 'Next', size: 'mid' },
  { file: 'gitmalybalon', label: 'Git', size: 'small' },
  { file: 'htmlmalybalon', label: 'HTML', size: 'small' },
  { file: 'figmamalybalon', label: 'Figma', size: 'small' },
  { file: 'firebasemalybalon', label: 'Firebase', size: 'small' },
];

/**
 * Plaques shown in the About room.
 *
 * These were award certificates in the upstream design. This site has no awards
 * to display, so they carry **factual open-source milestones instead** — do not
 * put fabricated credentials here. Each plaque needs `file` (art), `title`, `sub`,
 * plus `url`/`date` which the About room links out to.
 */
export const awards = [
  { file: 'plaque-open-source', category: 'release', title: 'OPEN SOURCE', sub: 'wu5-dev-flow', url: 'https://github.com/WenOwen/wu5-dev-flow', date: '2026-07-19' },
  { file: 'plaque-stars', category: 'release', title: '17 STARS', sub: 'wu5-dev-flow', url: 'https://github.com/WenOwen/wu5-dev-flow', date: '2026-07-19' },
  { file: 'plaque-mit', category: 'release', title: 'MIT LICENSED', sub: 'developer tooling', url: 'https://github.com/WenOwen?tab=repositories', date: '2026-08-11' },
  { file: 'plaque-python', category: 'release', title: 'PYTHON', sub: 'agent systems', url: 'https://github.com/WenOwen/yongxu', date: '2026-08-11' },
  { file: 'plaque-research', category: 'milestone', title: 'RESEARCH', sub: 'ML pipelines', url: 'https://github.com/WenOwen/wu5-research', date: '2026-04-24' },
  { file: 'plaque-aero', category: 'milestone', title: 'AERODYNAMICS', sub: 'delta learning', url: 'https://github.com/WenOwen/DeepDelta-Aero', date: '2026-04-02' },
  { file: 'plaque-skills', category: 'milestone', title: 'SKILL ROUTING', sub: 'entropy analysis', url: 'https://github.com/WenOwen/entropy-skills', date: '2026-07-25' },
];

/* ------------------------------------------------------------------ *
 * Studio room — content on the floating screens.
 * `platform` keeps the original layout ids (tv / monitor / phone);
 * only the labels shown to visitors change.
 * ------------------------------------------------------------------ */
export const studioPlatforms = {
  youtube: { label: 'OPEN SOURCE', color: '#24292f', accentColor: '#57606a', icon: '◆', shape: 'tv' },
  blog: { label: 'NOTES', color: '#3b6ea5', accentColor: '#2d5580', icon: '✎', shape: 'monitor' },
  tiktok: { label: 'TOOLING', color: '#2f8f83', accentColor: '#226b62', icon: '⚙', shape: 'phone' },
};

export const studioContent = [
  {
    id: 'os-001', platform: 'youtube', art: 'tvfront_devflow',
    title: 'wu5-dev-flow — spec-first development that leaves an audit trail',
    description: 'An SDD + strict TDD loop with safe Git checkpoints, packaged as a portable skill.',
    url: 'https://github.com/WenOwen/wu5-dev-flow', date: '2026-07-19', views: '★ 17', duration: 'skill',
  },
  {
    id: 'os-002', platform: 'youtube', art: 'tvfront_yongxu',
    title: 'yongxu — an operating system skeleton for an AI company',
    description: 'Companies, agents, tasks, governance and evolution modelled as primitives.',
    url: 'https://github.com/WenOwen/yongxu', date: '2026-08-11', views: 'Python', duration: 'repo',
  },
  {
    id: 'nt-001', platform: 'blog', art: 'monitorfront_entropy',
    title: 'Measuring entropy in a local Agent Skills collection',
    description: 'Routing conflicts, capability overlap, and which skills to merge or retire.',
    url: 'https://github.com/WenOwen/entropy-skills', date: '2026-07-25', readTime: '8 min',
  },
  {
    id: 'nt-002', platform: 'blog', art: 'monitorfront_aero',
    title: 'Delta-learning for axial compressor blade aerodynamics',
    description: 'Predicting blade performance with neural surrogates instead of CFD sweeps.',
    url: 'https://github.com/WenOwen/DeepDelta-Aero', date: '2026-04-02', readTime: '12 min',
  },
  {
    id: 'tl-001', platform: 'tiktok', art: 'phonefront_dukou',
    title: 'Publishing Markdown drafts without leaking them',
    description: 'A safe distribution tool for WeChat, Douyin and Bilibili.',
    url: 'https://github.com/WenOwen/wu5-dukou', date: '2026-07-18', views: 'JS', likes: 'tool',
  },
  {
    id: 'tl-002', platform: 'tiktok', art: 'phonefront_translate',
    title: 'One-click EN→ZH translation in the browser',
    description: 'A small Chrome extension for reading technical docs.',
    url: 'https://github.com/WenOwen/chrome-translate-extension', date: '2026-04-22', views: 'JS', likes: 'ext',
  },
];

/* ------------------------------------------------------------------ *
 * SEO — per-room title/description, consumed by useDocumentMeta + index.html
 * ------------------------------------------------------------------ */
export const seo = {
  null: {
    path: '/',
    title: 'wu5 — Creative 3D Portfolio',
    description:
      'Interactive 3D portfolio of wu5 — AI engineering, agent systems and research tooling, explored through a hand-drawn WebGL corridor.',
  },
  about: {
    path: '/about',
    title: 'About — wu5 Portfolio',
    description:
      'wu5 builds AI engineering systems, agent tooling and research pipelines. Skills across Python, TypeScript, React, Three.js and GSAP.',
  },
  gallery: {
    path: '/gallery',
    title: 'Projects — wu5 Portfolio',
    description:
      'Selected open-source projects by wu5, hung as hand-drawn cards in an interactive 3D gallery you can flip and explore.',
  },
  studio: {
    path: '/studio',
    title: 'The Studio — wu5 Portfolio',
    description:
      'Repositories, notes and tooling by wu5, displayed on floating screens inside an immersive 3D studio.',
  },
  contact: {
    path: '/contact',
    title: 'Contact — wu5 Portfolio',
    description:
      'Get in touch with wu5 — GitHub, LinkedIn and email, found among the signposts of an interactive 3D contact room.',
  },
};

/* ------------------------------------------------------------------ *
 * Door labels — the pictogram drawn on each door leaf
 * ------------------------------------------------------------------ */
export const doorKinds = {
  projekty: { label: 'PROJECTS' },
  about: { label: 'ABOUT' },
  kontakt: { label: 'CONTACT' },
  social: { label: 'SOCIAL' },
};
